/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dgame;

import javax.swing.JLabel;
public class playGame extends javax.swing.JFrame {
    Data data = new Data();
    RunningGame RG = new RunningGame();
    /**
     * Creates new form playGame
     */
    public playGame() {
        initComponents();
            buttonGroup1.add(easy);
            buttonGroup1.add(medium);
            buttonGroup1.add(hard);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        PlayerName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        easy = new javax.swing.JRadioButton();
        medium = new javax.swing.JRadioButton();
        hard = new javax.swing.JRadioButton();
        Jplay = new javax.swing.JButton();
        selectLevel = new javax.swing.JLabel();
        jLevel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 250));

        jLabel1.setText("Welcome to Dungen Game");

        jLabel2.setText("Select Level");

        easy.setText("Easy");

        medium.setText("Medium");

        hard.setText("Hard");

        Jplay.setText("Play");
        Jplay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JplayMouseClicked(evt);
            }
        });

        selectLevel.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        selectLevel.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(easy)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Jplay)
                                .addGap(18, 18, 18)
                                .addComponent(jLevel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(medium)
                                .addGap(18, 18, 18)
                                .addComponent(hard)))
                        .addGap(18, 18, 18)
                        .addComponent(selectLevel, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PlayerName, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(easy)
                    .addComponent(medium)
                    .addComponent(hard)
                    .addComponent(selectLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jplay)
                    .addComponent(jLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 128, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JplayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JplayMouseClicked
        // TODO add your handling code here:
        RG.initGame();
        if(easy.isSelected()){
            Data.healthPotionDropChance = 75;
            jLevel.setText(String.valueOf(Data.healthPotionDropChance));
            selectLevel.setText("");
            this.setVisible(false);
            RG.setVisible(true);
        }
        else if(medium.isSelected()){
            Data.healthPotionDropChance = 50;
            jLevel.setText(String.valueOf(Data.healthPotionDropChance));
            selectLevel.setText("");
            this.setVisible(false);
            RG.setVisible(true);
        }
        else if(hard.isSelected()){
            Data.healthPotionDropChance = 25;
            jLevel.setText(String.valueOf(Data.healthPotionDropChance));
            selectLevel.setText("");
            this.setVisible(false);
            RG.setVisible(true);
        }
        else {
            selectLevel.setText("Please Select Level!");
        }
    }//GEN-LAST:event_JplayMouseClicked

    /**
     * @param args the command line arguments
     */
   
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jplay;
    public javax.swing.JLabel PlayerName;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton easy;
    private javax.swing.JRadioButton hard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLevel;
    private javax.swing.JRadioButton medium;
    private javax.swing.JLabel selectLevel;
    // End of variables declaration//GEN-END:variables
}
